import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { GraduationCap, KeyRound, Pencil, Plus, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import { studentsApi } from "@/api/students";
import { apiErrorMessage } from "@/api/client";
import type { StudentCreate, StudentOut } from "@/types/student";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { DataTable, type Column } from "@/components/ui/DataTable";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { Switch } from "@/components/ui/Switch";

const empty: StudentCreate = { register_number: "", application_number: "", stage: "applicant", tenth_mark: undefined, twelfth_mark: undefined, diploma_mark: undefined, is_diploma: false, profile: { name: "", phone: "", gender: "" } };
export function StudentsPage() {
  const qc = useQueryClient(); const { data: students = [], isLoading } = useQuery({ queryKey: ["students"], queryFn: () => studentsApi.list() });
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<StudentOut | null>(null); const [form, setForm] = useState<StudentCreate>(empty); const [deleting, setDeleting] = useState<StudentOut | null>(null);
  const save = useMutation({ mutationFn: () => editing ? studentsApi.update(editing.id, form) : studentsApi.create(form), onSuccess: () => { qc.invalidateQueries({ queryKey: ["students"] }); toast.success(editing ? "Student updated" : "Student created"); setOpen(false); }, onError: (e) => toast.error(apiErrorMessage(e, "Could not save student")) });
  const remove = useMutation({ mutationFn: studentsApi.remove, onSuccess: () => { qc.invalidateQueries({ queryKey: ["students"] }); setDeleting(null); toast.success("Student deleted"); }, onError: (e) => toast.error(apiErrorMessage(e, "Could not delete student")) });
  const login = useMutation({ mutationFn: (id: number) => studentsApi.createLogin(id), onSuccess: (result) => { qc.invalidateQueries({ queryKey: ["students"] }); toast.success(`Login: ${result.username}${result.temporary_password ? ` · temporary password: ${result.temporary_password}` : ""}`, { duration: 12000 }); }, onError: (e) => toast.error(apiErrorMessage(e, "Could not create login")) });
  function show(s?: StudentOut) { setEditing(s ?? null); setForm(s ? { register_number: s.register_number ?? "", application_number: s.application_number ?? "", stage: s.stage as "applicant" | "enrolled", tenth_mark: s.tenth_mark ?? undefined, twelfth_mark: s.twelfth_mark ?? undefined, diploma_mark: s.diploma_mark ?? undefined, is_diploma: s.is_diploma, profile: { name: s.profile?.name ?? "", phone: s.profile?.phone ?? "", gender: s.profile?.gender ?? "" } } : empty); setOpen(true); }
  function submit(e: FormEvent) { e.preventDefault(); save.mutate(); }
  const cols: Column<StudentOut>[] = [{ header: "Student", accessor: (s) => <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-gradient-to-br from-brand-500 to-accent-500"><GraduationCap className="size-4" /></div><div><p className="font-medium text-slate-100">{s.profile?.name ?? "Unnamed"}</p><p className="text-xs text-slate-500">{s.register_number || s.application_number || `#${s.id}`}</p></div></div> }, { header: "Stage", accessor: (s) => <Badge variant={s.stage === "enrolled" ? "success" : "warning"}>{s.stage}</Badge> }, { header: "Marks", accessor: (s) => <span className="text-slate-400">10th {s.tenth_mark ?? "—"} · 12th {s.twelfth_mark ?? "—"}</span> }, { header: "Login", accessor: (s) => <Badge variant={s.has_login ? "success" : "neutral"} dot>{s.has_login ? "Provisioned" : "Not created"}</Badge> }];
  return <div><PageHeader title="Students" description="Manage applicants, enrolled students, and their learning accounts." actions={<Button onClick={() => show()}><Plus className="size-4" /> Add Student</Button>} /><DataTable columns={cols} data={students} keyExtractor={(s) => s.id} loading={isLoading} emptyTitle="No students yet" rowActions={(s) => <><button disabled={s.has_login || login.isPending} title="Create login" onClick={() => login.mutate(s.id)} className="rounded-lg p-2 text-slate-400 hover:text-brand-300 disabled:opacity-30"><KeyRound className="size-4" /></button><button onClick={() => show(s)} className="rounded-lg p-2 text-slate-400 hover:text-white"><Pencil className="size-4" /></button><button onClick={() => setDeleting(s)} className="rounded-lg p-2 text-slate-400 hover:text-danger-500"><Trash2 className="size-4" /></button></>} />
  <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Edit Student" : "New Student"} size="lg"><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input label="Full name" required value={form.profile.name} onChange={(e) => setForm({ ...form, profile: { ...form.profile, name: e.target.value } })} /><Input label="Phone" value={form.profile.phone ?? ""} onChange={(e) => setForm({ ...form, profile: { ...form.profile, phone: e.target.value } })} /><Input label="Register number" value={form.register_number ?? ""} onChange={(e) => setForm({ ...form, register_number: e.target.value })} /><Input label="Application number" value={form.application_number ?? ""} onChange={(e) => setForm({ ...form, application_number: e.target.value })} /><Select label="Stage" value={form.stage} onChange={(e) => setForm({ ...form, stage: e.target.value as "applicant" | "enrolled" })} options={[{ value: "applicant", label: "Applicant" }, { value: "enrolled", label: "Enrolled" }]} /><Select label="Gender" placeholder="Not specified" value={form.profile.gender ?? ""} onChange={(e) => setForm({ ...form, profile: { ...form.profile, gender: e.target.value } })} options={[{ value: "male", label: "Male" }, { value: "female", label: "Female" }, { value: "other", label: "Other" }]} /><Input label="10th mark" type="number" min={0} max={100} value={form.tenth_mark ?? ""} onChange={(e) => setForm({ ...form, tenth_mark: Number(e.target.value) || undefined })} /><Input label="12th mark" type="number" min={0} max={100} value={form.twelfth_mark ?? ""} onChange={(e) => setForm({ ...form, twelfth_mark: Number(e.target.value) || undefined })} /></div><Switch checked={form.is_diploma} onChange={(is_diploma) => setForm({ ...form, is_diploma })} label="Diploma student" /><div className="flex gap-3"><Button type="button" variant="glass" className="flex-1" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" className="flex-1" loading={save.isPending}>Save</Button></div></form></Modal><ConfirmDialog open={!!deleting} onClose={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id)} title="Delete this student?" description="Deletion is blocked when the student has history." confirmLabel="Delete" loading={remove.isPending} /></div>;
}
